Fail if can't download; use GITHUB_TOKEN if set

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,15 +1,26 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
+shopt -s inherit_errexit 2>/dev/null || true
 
 [[ -z ${ASDF_INSTALL_TYPE+x} ]] && echo "ASDF_INSTALL_TYPE is required" && exit 1
 [[ -z ${ASDF_INSTALL_VERSION+x} ]] && echo "ASDF_INSTALL_VERSION is required" && exit 1
 [[ -z ${ASDF_INSTALL_PATH+x} ]] && echo "ASDF_INSTALL_PATH is required" && exit 1
 
-install() {
+function gh_curl() {
+	if [[ -n ${GITHUB_TOKEN:-} ]]; then
+		curl -fLsS -H "Authorization: token ${GITHUB_TOKEN}" "$@"
+	else
+		curl -fLsS "$@"
+	fi
+}
+
+function install() {
+	# set -x
 	local install_type=$1
 	[[ ${install_type} != "version" ]] && echo "install type, ${install_type}, is not supported" && exit 1
 
+	local prefix="v"
 	local version=$2
 	local install_path=$3
 
@@ -24,29 +35,44 @@ install() {
 	local bin_install_path="${install_path}/bin"
 
 	local platform
-	platform=$(uname | tr '[:upper:]' '[:lower:]')
+	platform=$(uname -s)
 
 	local arch
 	arch=$(uname -m)
 	case "${arch}" in
-	x86_64) arch="amd64" ;;
-	aarch64) arch="arm64" ;;
-	arm*) arch="arm" ;;
+	aarch64) arch=arm64 ;;
+	x86_64) arch=amd64 ;;
 	esac
 
 	local download_url
-	download_url="https://github.com/justjanne/powerline-go/releases/download/v${version}/powerline-go-${platform}-${arch}"
 
-	echo "Downloading powerline-go from ${download_url}"
+	local repo="justjanne/powerline-go"
+	local download_filename="powerline-go-${platform}-${arch}"
+
+	if [[ -n ${GITHUB_TOKEN:-} ]]; then
+		local asset_url
+		asset_url="https://api.github.com/repos/${repo}/releases/tags/${prefix}${version}"
+		download_url=$(gh_curl -H "Accept: application/vnd.github.v3.raw" "${asset_url}" | jq -r ".assets | map(select(.name == \"${download_filename}\"))[0].url")
+		if [[ ${download_url} == null ]]; then
+			echo "Asset ${download_filename} not found in a release."
+			exit 1
+		fi
+	else
+		download_url="https://github.com/${repo}/releases/download/${prefix}${version}/${download_filename}"
+	fi
+
+	echo "Downloading from ${download_url}"
+
+	mkdir -p "${tmp_download_dir}"
 
 	pushd "${tmp_download_dir}" >/dev/null
 
-	curl -sLO "${download_url}"
+	gh_curl -H "Accept: application/octet-stream" -o "${download_filename}" "${download_url}"
 
 	mkdir -p "${bin_install_path}"
 
-	cp powerline-go-* "${bin_install_path}/powerline-go"
-	chmod +x "${bin_install_path}/powerline-go"
+	tar zxf "${download_filename}"
+	cp -fp "${download_filename}" "${bin_install_path}/powerline-go"
 
 	popd >/dev/null
 }
