Verify checksum

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -10,6 +10,8 @@ shopt -s inherit_errexit 2>/dev/null || true
 function gh_curl() {
 	if [[ -n ${GITHUB_TOKEN-} ]]; then
 		curl -fLsS -H "Authorization: token ${GITHUB_TOKEN}" "$@"
+	elif [[ -n ${GITHUB_API_TOKEN-} ]]; then
+		curl -fLsS -H "Authorization: token ${GITHUB_API_TOKEN}" "$@"
 	else
 		curl -fLsS "$@"
 	fi
@@ -35,39 +37,67 @@ function install() {
 	local bin_install_path="${install_path}/bin"
 
 	local platform
-	platform=$(uname -s | tr 'A-Z' 'a-z')
+	platform=$(uname -s | tr '[:upper:]' '[:lower:]')
 
 	local arch
 	arch=$(uname -m)
 	case "${arch}" in
-	aarch64) arch=arm64 ;;
+	aarch64 | arm64) arch=arm64 ;;
+	arm*) arch=arm ;;
+	i?86) arch=386 ;;
 	x86_64) arch=amd64 ;;
 	esac
 
 	local download_url
+	local checksum_url
 
 	local repo="justjanne/powerline-go"
 	local download_filename="powerline-go-${platform}-${arch}"
+	local checksum_filename="checksums.txt"
 
-	if [[ -n ${GITHUB_TOKEN-} ]]; then
+	if [[ -n ${GITHUB_TOKEN-} ]] || [[ -n ${GITHUB_API_TOKEN-} ]]; then
 		local asset_url
 		asset_url="https://api.github.com/repos/${repo}/releases/tags/${prefix}${version}"
 		download_url=$(gh_curl -H "Accept: application/vnd.github.v3.raw" "${asset_url}" | jq -r ".assets | map(select(.name == \"${download_filename}\"))[0].url")
 		if [[ ${download_url} == null ]]; then
-			echo "Asset ${download_filename} not found in a release."
+			echo "Asset ${download_filename} not found in a release ${prefix}${version}."
 			exit 1
 		fi
+		case "${version}" in
+		0.* | 1.?.* | 1.1?.* | 1.2[0-3].* | 1.2[0-3]) ;;
+		*)
+			checksum_url=$(gh_curl -H "Accept: application/vnd.github.v3.raw" "${asset_url}" | jq -r ".assets | map(select(.name == \"${checksum_filename}\"))[0].url")
+			if [[ ${checksum_url} == null ]]; then
+				echo "Asset ${checksum_filename} not found in a release ${prefix}${version}."
+				exit 1
+			fi
+			;;
+		esac
 	else
 		download_url="https://github.com/${repo}/releases/download/${prefix}${version}/${download_filename}"
+		case "${version}" in
+		0.* | 1.?.* | 1.1?.* | 1.2[0-3].* | 1.2[0-3]) ;;
+		*)
+			checksum_url="https://github.com/${repo}/releases/download/${prefix}${version}/${checksum_filename}"
+			;;
+		esac
 	fi
 
-	echo "Downloading from ${download_url}"
+	echo "Downloading ${download_filename} from release ${prefix}${version} from ${download_url}"
 
 	mkdir -p "${tmp_download_dir}"
 
 	pushd "${tmp_download_dir}" >/dev/null
 
 	gh_curl -H "Accept: application/octet-stream" -o "${download_filename}" "${download_url}"
+
+	if [[ -n ${checksum_url-} ]]; then
+		if command -v shasum >/dev/null; then
+			gh_curl -H "Accept: application/octet-stream" "${checksum_url}" | awk "\$2 == \"${download_filename}\" {print}" | shasum -a 256 -c
+		elif command -v sha256sum >/dev/null; then
+			gh_curl -H "Accept: application/octet-stream" "${checksum_url}" | awk "\$2 == \"${download_filename}\" {print}" | sha256sum -c
+		fi
+	fi
 
 	mkdir -p "${bin_install_path}"
 
